"""
Django settings for pymantra_api project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", default='foo')


ROOT_DOMAIN = os.environ.get('ROOT_DOMAIN', default='')
if os.environ.get("HTTPS", False):
    SESSION_COOKIE_PATH = f"{ROOT_DOMAIN}"
    CSRF_COOKIE_PATH = f"{ROOT_DOMAIN}"
    # this (usually) means we are in a production setting => always turn debug
    # off as a precaution
    DEBUG = 0
else:
    DEBUG = int(os.environ.get("DJANGO_DEBUG", default=0))
CSRF_COOKIE_SESSION = True
SESSION_COOKIE_SECURE = True

ALLOWED_HOSTS = os.environ.get(
    "DJANGO_ALLOWED_HOSTS", default='127.0.0.1 localhost').split(" ")

NEO4J_DB = {
    'user': os.environ.get("NEO4J_USER", default='foo'),
    'password': os.environ.get("NEO4J_PASSWORD", default='bar'),
    'protocol': 'bolt',
    'host': 'neo4j-db',
    'port': '7687',
    'import_dir': '/var/lib/neo4j/import',
}

SQL_DB = {
    'user': 'root',
    'password': os.environ.get("SQL_PASSWORD", default='bar'),
    'protocol': 'mysql',
    'host': 'sql-db',
    'port': '3306',
    'django_database_name': os.environ.get("SQL_DATABASE", default='foo'),
    'import_dir': '/var/lib/mysql-files',
}

DJANGO_ADMIN = {
    'user': os.environ.get("DJANGO_ADMIN_USER", "foo456"),
    'password': os.environ.get("DJANGO_ADMIN_PASSWORD", "bar123"),
    'email': os.environ.get("DJANGO_ADMIN_EMAIL", "test@nonexisting.com")
}


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'database',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pymantra_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pymantra_api.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': SQL_DB.get('django_database_name'),
        'USER': SQL_DB.get('user'),
        'PASSWORD': SQL_DB.get('password'),
        'HOST': 'sql-db',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
